image:
  pullPolicy: IfNotPresent
  # Overrides the image tag with the latest release tag value
  tag: "latest"

resources:
  limits:
    memory: 750Mi
    cpu: 1000m
  requests:
    memory: 512Mi
    cpu: 100m

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

settings:
  profile: PLUGINS
#  logstash:
#    host: logstash
#    port: "5008"

env:
  - name: JAVA_TOOL_OPTIONS
    value: -Xss256k -Xms256m -Xmx512m -XX:ReservedCodeCacheSize=128M

configmap:
  enabled: true
  extraScrapeConfigs:
    application.properties: |
      logging.level.root=INFO
      spring.datasource.url=jdbc:postgresql://postgres:5432/ai_service
      spring.datasource.username=user_ai_service
      spring.datasource.password=password_ai_service
      chat-gpt.model=gpt-4o
      chat-gpt.temperature=1.0
