image:
  pullPolicy: IfNotPresent
  # Overrides the image tag with the latest release tag value
  tag: "latest"

resources:
  limits:
    memory: 750Mi
    cpu: 300m
  requests:
    memory: 750Mi
    cpu: 50m

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

settings:
  profile: PLUGINS

env:
  - name: JAVA_TOOL_OPTIONS
    value: -Xss256k -Xms256m -Xmx512m -XX:ReservedCodeCacheSize=128M
#  - name: LOGSTASH_HOST
#    value: logstash
#  - name: LOGSTASH_PORT
#    value: "5008"

configmap:
  enabled: true
  extraScrapeConfigs:
    application.properties: |
      spring.datasource.url=jdbc:postgresql://postgres:5432/ai_service
      spring.datasource.username=user_ai_service
      spring.datasource.password=password_ai_service
      chat-gpt.model=gpt-4o
      chat-gpt.temperature=1.0
