image:
  repository: stripo/coediting-core-service
  pullPolicy: IfNotPresent
  # Override the image tag with the release tag value
  tag: "latest"

nameOverride: "coediting-core-service"

resources:
  limits:
    memory: 700Mi
    cpu: 2000m
  requests:
    memory: 300Mi
    cpu: 1000m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetMemoryUtilizationPercentage: 80
  targetCPUUtilizationPercentage: 80

settings:
  profile: PLUGINS
  accessControlAllowOrigin: "*"
  changedEmailNotificationDebounceTime: "3s"
  auth:
    base64:
      htmlCssV1Request:
        username: coeditingUser
        password: secret
  golang:
    # Depends on cpu limit. 2 for 2000m
    goMaxProcs: "2"
    # Depends on memory limit (~90%). 600 for 700m
    goMemLimit: 600MiB
  tiDb:
    host: db_host
    port: 4000
    username: db_user
    password: db_password
    databaseName: stripo_coediting_db
  nats:
    url: "nats://example-nats-1.svc.stripo.email:4222, nats://example-nats-2.svc.stripo.email:4222, nats://example-nats-3.svc.stripo.email:4222"
    user: nats_user
    password: nats_password
  redis:
    #    clusterUrl: "example-redis-001.euw1.cache.amazonaws.com:6379,example-redis-002.euw1.cache.amazonaws.com:6379"
    host: redis-master
    port: "6379"
    password: secret
  rateLimits:
    ws:
      defaultMessage: "{\"limit\": 1080, \"duration_seconds\": 60, \"burst\": 10}"
      cursorMessage: "{\"limit\": 18000, \"duration_seconds\": 60, \"burst\": 100}"
    rest:
      defaultRequest: "{\"limit\": 90, \"duration_seconds\": 60, \"burst\": 5}"
      compileRequest: "{\"limit\": 10, \"duration_seconds\": 60, \"burst\": 1}"
      htmlCssV1Request: "{\"limit\": 10, \"duration_seconds\": 60, \"burst\": 1}"
#  logstash:
#    host: logstash
#    port: "5008"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: plugins.example.com
      paths:
        - path: /coediting/(.*)
          pathType: Prefix
