image:
  pullPolicy: IfNotPresent
  # Overrides the image tag with the latest release tag value
  tag: "latest"

resources:
  limits:
    memory: 1000Mi
    cpu: 1000m
  requests:
    memory: 750Mi
    cpu: 100m

# In case of autoscaling is disabled
#replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

settings:
  profile: PLUGINS
#  logstash:
#    host: logstash
#    port: "5008"

env: 
  - name: JAVA_TOOL_OPTIONS
    value: -Xss256k -Xms400m -Xmx512m -XX:ReservedCodeCacheSize=128M

configmap:
  enabled: true
  extraScrapeConfigs:
    application.properties: |
      logging.level.root=INFO
      spring.datasource.url=jdbc:postgresql://postgres:5432/stripo_plugin_local_custom_blocks
      spring.datasource.username=user_custom_blocks
      spring.datasource.password=password_custom_blocks
      plugin.service.documentsUrl=http://stripo-plugin-documents-service:8080
            
