image:
  pullPolicy: IfNotPresent
  # Overrides the image tag with the latest release tag value
  tag: "latest"

resources:
  limits:
    memory: 500Mi
    cpu: 1000m
  requests:
    memory: 500Mi
    cpu: 10m

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

settings:
  profile: PLUGINS
#  logstash:
#    host: logstash
#    port: "5008"

env: 
  - name: JAVA_TOOL_OPTIONS
    value: -Xss256k -Xms128m -Xmx256m -XX:ReservedCodeCacheSize=128M

configmap:
  enabled: true
  extraScrapeConfigs:
    application.properties: |
      logging.level.root=INFO
      spring.datasource.url=jdbc:postgresql://postgres:5432/stripo_plugin_local_securitydb
      spring.datasource.username=user_securitydb
      spring.datasource.password=password_securitydb
      auth.passwordV2=secret
