image:
  pullPolicy: IfNotPresent
  # Overrides the image tag with the latest release tag value
  tag: "latest"

resources:
  limits:
    memory: 1200Mi
    cpu: 500m
  requests:
    memory: 1200Mi
    cpu: 200m

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

settings:
  profile: PLUGINS

env: 
  - name: JAVA_TOOL_OPTIONS
    value: -Xss256k -Xms400m -Xmx512m -XX:MaxMetaspaceSize=256m -XX:-UseGCOverheadLimit -Djava.net.preferIPv4Stack=true
#  - name: LOGSTASH_HOST
#    value: logstash
#  - name: LOGSTASH_PORT
#    value: "5008"

configmap:
  enabled: true
  extraScrapeConfigs:
    application.properties: |
      logging.level.root=INFO
      spring.datasource.url=jdbc:postgresql://postgres:5432/stripo_plugin_local_html_gen
      spring.datasource.username=user_html_gen
      spring.datasource.password=password_html_gen
      stripo.security.service.baseUrl=http://stripo-security-service:8080
      stripo.security.service.passwordV2=secret
      rate.limit.enabled=false
